---
# Setup default propreties we want on all/most containers
x-default-container: &default-container
  user: 1000:1000
  group_add:
    - "109"
  environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Berlin
  restart: unless-stopped

# containers on the mediarr nework, also have access to specific volumes
x-mediarr-container: &mediarr-container
  <<: *default-container
  networks:
    - mediarr
  volumes:
    - /mnt/Media:/mnt/media
    - /mnt/Media/downloads:/mnt/downloads

services:
  wireguard:
    #<<: *default-container
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /mnt/srvconf/wireguard:/config
      - /lib/modules:/lib/modules # For kernel modules
    ports:
      - "51820:51820/udp"
      - 8080:8080 # Following ports moved from qbittorrent
      - 6881:6881
      - 6881:6881/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    depends_on:
      - qbittorrent
    networks:
      - mediarr
  syncthing:
    networks:
      - mediarr
    container_name: syncthing
    image: syncthing/syncthing:latest
    hostname: syncthing
    volumes:
      - jellyfin-etc:/srv/jellyfin/etc
      - jellyfin-lib:/srv/jellyfin/lib
      - /mnt/srvconf/syncthing:/var/syncthing/config
  jellyfin:
    <<: *default-container
    container_name: jellyfin
    hostname: jellyfin
    image: jellyfin/jellyfin
    environment:
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      #- JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      #- JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - jellyfin-etc:/etc/jellyfin
      - jellyfin-lib:/var/lib/jellyfin
      - jellyfin-cache:/var/cache/jellyfin
      - /var/log/jellyfin/:/var/log/jellyfin
      - /etc/timezone:/etc/timezone
      - /mnt/Media:/mnt/media
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
      - 7359:7359/udp
    #devices:
      #- /dev/dri/renderD128:/dev/dri/renderD128
  #firefox:
    #<<: *default-container
    #image: lscr.io/linuxserver/firefox:latest
    #container_name: firefox
    #security_opt:
      #- seccomp:unconfined
    #environment:
      ##- DRINODE=/dev/dri/renderD128
      #- DISABLE_IPV6=true
      #- DOCKER_MODS=linuxserver/mods:firefox-fonts
    #volumes:
      #- ./configs/firefox:/config
    #ports:
      #- 3001:3001
    #networks:
      #- firefox
    #shm_size: "1gb"
    ##devices:
      ##- /dev/dri/renderD128:/dev/dri/renderD128
  ##duplicati:
    ##image: lscr.io/linuxserver/duplicati:latest
    ##container_name: duplicati
    ##volumes:
      ##- ./configs/duplicati/config:/config
      ##- ./configs:/source
      ##- ./docker-compose.yml:/source/docker-compose.yml
      ##- ./configs/duplicati/restore:/restore
    ##networks:
      ##- duplicati
    ##ports:
  #bazarr:
    #<<: *mediarr-container
    #image: lscr.io/linuxserver/bazarr:latest
    #container_name: bazarr
    #hostname: bazarr
    #volumes:
      #- ./configs/mediarr/bazarr:/config
    #ports:
      #- 6767:6767
    #depends_on:
      #- sonarr
      #- radarr
  #jellyseerr:
    #<<: *mediarr-container
    #image: fallenbagel/jellyseerr:latest
    #container_name: jellyseerr
    #hostname: jellyseerr
    #ports:
      #- 5055:5055
    #volumes:
      #- ./configs/mediarr/jellyseerr:/app/config
    #depends_on:
      #- sonarr
      #- radarr
  prowlarr:
    <<: *mediarr-container
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - /mnt/srvconf/prowlarr:/config
    ports:
      - 9696:9696
    depends_on:
      - flaresolverr
  flaresolverr:
    <<: *mediarr-container
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    restart: unless-stopped
  qbittorrent:
    #<<: *mediarr-container
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    #hostname: qbittorrent
    environment:
      - WEBUI_PORT=8080
    volumes:
      - /mnt/srvconf/qbittorrent:/config
      - /mnt/Media/downloads:/downloads
    #ports: # Moved to wireguard stack via network_mode
      #- 8080:8080
      #- 6881:6881
      #- 6881:6881/udp
    network_mode: service:wireguard
  radarr:
    <<: *mediarr-container
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - /mnt/srvconf/radarr:/config
    ports:
      - 7878:7878
    depends_on:
      - prowlarr
      - qbittorrent
      - jellyfin
  #readarr:
    #<<: *mediarr-container
    #image: lscr.io/linuxserver/readarr:develop
    #container_name: readarr
    #hostname: readarr
    #volumes:
      #- ./mediarr/readarr:/config
    #ports:
      #- 8787:8787
    #depends_on:
      #- prowlarr
      #- qbittorrent
  sonarr:
    <<: *mediarr-container
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - /mnt/srvconf/sonarr:/config
    depends_on:
      - prowlarr
      #- qbittorrent
      - jellyfin
    ports:
      - 8989:8989
networks:
  #firefox:
    #driver: bridge
  #duplicati:
    #driver: bridge
  mediarr:
    driver: bridge
volumes:
  jellyfin-cache:
    driver: local
  jellyfin-lib:
    driver: local
  jellyfin-etc:
    driver: local
  #myMedia:
    #driver: local
    #driver_opts:
      #type: none
      #o: bind
      #device: /mnt/media
  #myDlFolders:
    #driver: local
    #driver_opts:
      #type: none
      #o: bind
      #device: /mnt/HDD/downloads
